### ISSUE TITLE
FileNotFoundError after trying to install GE-Proton in Steam Snap

### ISSUE THREAD

**Issue by Deewens** [DavidoTek/ProtonUp-Qt#368] opened 2024-04-02 20:01 UTC
Please fill out following when reporting a new bug:

**Describe the bug**  
I tried to install GE-Proton, the last version 9.2 I think. After the download finished, the program crashed with an error message. I tried to reopen the application, but now it won't open and give me an error message.

```
Traceback (most recent call last):
  File "/tmp/.mount_ProtonR87rBj/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_ProtonR87rBj/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_ProtonR87rBj/usr/lib/python3.8/site-packages/pupgui2/__main__.py", line 2, in <module>
    main()
  File "/tmp/.mount_ProtonR87rBj/usr/lib/python3.8/site-packages/pupgui2/pupgui2.py", line 571, in main
    MainWindow()
  File "/tmp/.mount_ProtonR87rBj/usr/lib/python3.8/site-packages/pupgui2/pupgui2.py", line 109, in __init__
    self.update_ui()
  File "/tmp/.mount_ProtonR87rBj/usr/lib/python3.8/site-packages/pupgui2/pupgui2.py", line 230, in update_ui
    global_ctool_name: str = get_steam_global_ctool_name(install_loc.get('vdf_dir'))
  File "/tmp/.mount_ProtonR87rBj/usr/lib/python3.8/site-packages/pupgui2/steamutil.py", line 206, in get_steam_global_ctool_name
    d = get_steam_vdf_compat_tool_mapping(vdf.load(open(config_vdf_file)))
FileNotFoundError: [Errno 2] No such file or directory: '/home/deewens/snap/steam/common/.steam/root/config/config.vdf'
```

**To Reproduce**  
1. Open GE-Proton AppImage
2. Install GE-Proton last version for the Steam Snap
3. You'll get an error message and the app will crash
4. If you try to reopen the AppImage, it won't and crash immediately with the error message describe above

**Expected behavior**  
No error message and GE-Proton to install in Steam.

**Screenshots**  

**Desktop (please complete the following information):**  
 - **Platform**: Desktop PC
 - **System**: Ubutun 23.10
 - **Version**: 2.9.1
 - **How did you install ProtonUp-Qt?**: AppImage

**Additional context**  
I'm running the Snap version of Steam, and tried to use the AppImage version of ProtonUp-Qt, because Ubuntu does not install Flatpak out-of-the box, and I don't want to install GNOME Software in addition to the Ubuntu Software.

**Terminal output**  
```
Open the Terminal app and type one of the following commands and press Enter (The app is called "Konsole" on Steam Deck):

If you installed ProtonUp-Qt via Flatpak (Discover on Steam Deck), type:
flatpak run net.davidotek.pupgui2

If you have downloaded the AppImage, navigate to the folder containing the AppImage file and type:
./ProtonUp-Qt*.AppImage

Try to replicate the bug and paste the text output of the command here afterwards.

```
pImage 
ProtonUp-Qt 2.9.1 by DavidoTek. Build Info: Official AppImage by DavidoTek.
Python 3.8.2 (default, Mar 13 2020, 10:14:16) [GCC 9.3.0], PySide 6.2.4
Platform: Ubuntu 23.10 Linux-6.5.0-26-generic-x86_64-with-glibc2.29
Warning: Ignoring WAYLAND_DISPLAY on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Loading locale en / en_US
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod D8VK (nightly)
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Northstar Proton (Titanfall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine)
Loaded ctmod Wine Tkg (Vanilla Wine)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Error: Could not get a list of all Steam apps: [Errno 2] No such file or directory: '/home/deewens/snap/steam/common/.steam/root/config/libraryfolders.vdf'
Traceback (most recent call last):
  File "/tmp/.mount_ProtonnXJhKR/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_ProtonnXJhKR/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_ProtonnXJhKR/usr/lib/python3.8/site-packages/pupgui2/__main__.py", line 2, in <module>
    main()
  File "/tmp/.mount_ProtonnXJhKR/usr/lib/python3.8/site-packages/pupgui2/pupgui2.py", line 571, in main
    MainWindow()
  File "/tmp/.mount_ProtonnXJhKR/usr/lib/python3.8/site-packages/pupgui2/pupgui2.py", line 109, in __init__
    self.update_ui()
  File "/tmp/.mount_ProtonnXJhKR/usr/lib/python3.8/site-packages/pupgui2/pupgui2.py", line 230, in update_ui
    global_ctool_name: str = get_steam_global_ctool_name(install_loc.get('vdf_dir'))
  File "/tmp/.mount_ProtonnXJhKR/usr/lib/python3.8/site-packages/pupgui2/steamutil.py", line 206, in get_steam_global_ctool_name
    d = get_steam_vdf_compat_tool_mapping(vdf.load(open(config_vdf_file)))
FileNotFoundError: [Errno 2] No such file or directory: '/home/deewens/snap/steam/common/.steam/root/config/config.vdf'

Gamepad error: No gamepad found.
```

**Comment by DavidoTek** [comment] 2024-04-03 17:57
Thanks for reporting.

Closed as duplicate of https://github.com/DavidoTek/ProtonUp-Qt/issues/353
Should be fixed with PR #356 and be available with the next release version of ProtonUp-Qt.

The issue also suggests that the Steam installation is invalid or not initialized. Have you started Steam at least once before using ProtonUp-Qt?

---

I noticed that the problem occurs with a native Steam installation in Issue #353, but with a Snap installation in this issue. Should be fixed in a future version nevertheless. Feel free to report if the issue is fixed in a future version.

**Closed by DavidoTek** 2024-04-03 17:57 UTC
Labels: bug
