### ISSUE TITLE
ProtonUp-QT Crashes on Steam Deck

### ISSUE THREAD

**Issue by billyjbryant** [DavidoTek/ProtonUp-Qt#112] opened 2022-08-22 17:41 UTC
**Describe the bug** 
On the Steam Deck, the latest version of ProtonUp-Qt installable (by default) crashes on launch with no debug or error output. 

**To Reproduce**  
1. Go to Desktop Mode on Steam Deck
2. Open the Applications Menu
3. Search for ProtonUp-Qt
4. Attempt to Launch the application
5. Application immediately crashes and closes its processes

**Expected behavior**  
I expect the application to launch successfully

**Screenshots**  
n/a

**Desktop (please complete the following information):**  
 - OS: [e.g. Ubuntu 20.04] SteamOS 3.3.1
 - Version [e.g. ProtonUp-Qt 2.5.0 AppImage or Flatpak] ProtonUp-Qt 2.7.0 Flatpak (SteamDeck Discover)

**Additional context**  
After initial installation the application launched one time with no issue. I was able to use it to install the latest version of ProtonGE 7.2.0; however, subsequent attempts to launch the application (after a SteamDeck Restart) fail. 

**Terminal output**  
```
Second instance of ProtonUp-Qt found!
```
I have checked running processes but the application is not running.

**Comment by DavidoTek** [comment] 2022-08-22 17:56
This is caused by a problem currently being solved (see https://github.com/DavidoTek/ProtonUp-Qt/pull/111)

To fix it for now, delete the folder `/tmp/pupgui2.a70200`

**Comment by billyjbryant** [comment] 2022-08-22 17:59
Thank you for the fast response @DavidoTek ! I will give that a shot :)

**Comment by billyjbryant** [comment] 2022-08-22 18:00
This did not correct the issue.

```
(deck@savitar ~)$ sudo rm -rf /tmp/pupgui*
(deck@savitar ~)$ flatpak run net.davidotek.pupgui2
ProtonUp-Qt 2.7.0 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.9.9 (main, Nov 10 2011, 15:00:00) [GCC 11.3.0], PySide 6.3.1
Platform: Linux-5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3-x86_64-with-glibc2.33
Second instance of ProtonUp-Qt found!
```

**Comment by DavidoTek** [comment] 2022-08-22 18:23
Oops, the folder for the Flatpak is different: `~/.var/app/net.davidotek.pupgui2/cache/tmp/pupgui2.a70200`

**Comment by yurikaka** [comment] 2022-08-23 05:43
I encountered this issue for multi times on my steam deck during the passed weekend, I did some serching and found the pid conflict chance is much higher in flatpak, since flatpak apps run in sandbox/namespace, they always get a very low pid like 2 or 3, so it's very likely to get a conflict when you run it next time.

**Comment by DavidoTek** [comment] 2022-08-23 16:34
Should be fixed with https://github.com/DavidoTek/ProtonUp-Qt/pull/111. Will be included in the next release.

**Closed by DavidoTek** 2022-08-23 16:34 UTC
Labels: bug
