### ISSUE TITLE
ProtonUp not working 

### ISSUE THREAD

**Issue by Vhaggx** [DavidoTek/ProtonUp-Qt#395] opened 2024-05-12 22:15 UTC
Please fill out following when reporting a new bug:

**Describe the bug**  
Nothing happens when I click on the AppImage file in the files, when I try to run it in cli I get an error:

ProtonUp-Qt 2.9.2 by DavidoTek. Build Info: Official AppImage by DavidoTek.
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0], PySide 6.7.0
Platform: Ubuntu 24.04 Linux-6.8.0-31-generic-x86_64-with-glibc2.39
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

Aborted (core dumped)

**To Reproduce**  
1. Try to open ProtonUp-Qt-2.9.2-x86_64.AppImage
2. Get error :(

**Expected behavior**  
For the app to work...

**Desktop (please complete the following information):**  
 - **Platform**: Laptop
 - **System**: Ubuntu 24.04 LTS
 - **Version**: ProtonUp-Qt 2.9.2
 - **How did you install ProtonUp-Qt?**: AppImage

**Additional context**  
I also installed it using flatpak but when I tried to run it it said that there is no module named pupgui2 

**Terminal output**  
```
ProtonUp-Qt 2.9.2 by DavidoTek. Build Info: Official AppImage by DavidoTek.
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0], PySide 6.7.0
Platform: Ubuntu 24.04 Linux-6.8.0-31-generic-x86_64-with-glibc2.39
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

Aborted (core dumped)
```
Ps: Im a total noob for Linux so I might not know a lot of stuff, if you need more information let me know (and also please tell me how to get it).

**Comment by sonic2kk** [comment] 2024-05-12 23:48
Seems like a duplicate of #378.

**Comment by DavidoTek** [comment] 2024-05-13 06:19
> sudo apt install libxcb-cursor0 is enough?

That should work with Debian. Seems to be a valid package: https://packages.debian.org/sid/amd64/libs/libxcb-cursor0

> I also installed it using flatpak but when I tried to run it it said that there is no module named pupgui2
> Ubuntu has some hoops you need to jump through to get Flatpaks to work, which may be why it didn't work.

Can you give us the Terminal output of running the Flatpak? That sounds strange and should be unrelated to the Linux distribution.

**Closed** 2024-05-13 06:19 UTC
Labels: bug
