### ISSUE TITLE
The application is crashing on start

### ISSUE THREAD

**Issue by Vitalya-code** [DavidoTek/ProtonUp-Qt#242] opened 2023-05-22 21:26 UTC
Please fill out following when reporting a new bug:

When i'm trying to start the application it's just crashing

  
1. Start the application 
2. See the error 

**Expected behavior**  
It should work, obviously

**Screenshots**  
Only terminal output

**Desktop (please complete the following information):**  
 - Laptop: Are you using a Steam Deck or a PC/Laptop?
 - Pop!_os 22.04: For example SteamOS 3.3 or Lubuntu 20.04
 - ProtonUp-Qt 2.8.0: For example ProtonUp-Qt 2.5.0
 - **Flatpak**: Discover app store / Flatpak / AppImage

**Additional context**  

**Terminal output**  

Open the Terminal app and type one of the following commands and press Enter (The app is called "Konsole" on Steam Deck):

If you installed ProtonUp-Qt via Flatpak (Discover on Steam Deck), type:
flatpak run net.davidotek.pupgui2

If you have downloaded the AppImage, navigate to the folder containing the AppImage file and type:
./ProtonUp-Qt*.AppImage

Try to replicate the bug and paste the text output of the command here afterwards.
```flatpak run net.davidotek.pupgui2
ProtonUp-Qt 2.8.0 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.10.6 (main, Nov 10 2011, 15:00:00) [GCC 12.2.0], PySide 6.4.3
Platform: KDE Flatpak runtime 5.15-21.08 Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35
Gtk-Message: 22:15:56.882: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:15:56.883: Failed to load module "canberra-gtk-module"
qt.qpa.qgnomeplatform: Could not find color scheme  ""
Qt: Session management error: None of the authentication protocols specified are supported
Loading locale en / en_US
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod D8VK (nightly)
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod NorthStar Proton (TitanFall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine)
Loaded ctmod Wine Tkg (Vanilla Wine)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Error: Could not get a list of all Steam apps: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/lib/python3.10/site-packages/pupgui2/__main__.py", line 2, in <module>
    main()
  File "/app/lib/python3.10/site-packages/pupgui2/pupgui2.py", line 549, in main
    MainWindow()
  File "/app/lib/python3.10/site-packages/pupgui2/pupgui2.py", line 108, in __init__
    self.update_ui()
  File "/app/lib/python3.10/site-packages/pupgui2/pupgui2.py", line 223, in update_ui
    get_steam_app_list(install_loc.get('vdf_dir'), cached=False)  # update app list cache
  File "/app/lib/python3.10/site-packages/pupgui2/steamutil.py", line 74, in get_steam_app_list
    apps.extend(get_steam_shortcuts_list(steam_config_folder, c))
UnboundLocalError: local variable 'c' referenced before assignment
Gamepad error: No gamepad found.
QThread: Destroyed while thread is still running
/app/bin/net.davidotek.pupgui2: line 3:     3 Aborted                 (core dumped) python3 -m pupgui2 "$@"
```

**Comment by DavidoTek** [comment] 2023-05-22 21:51
Duplicate of https://github.com/DavidoTek/ProtonUp-Qt/issues/226. Will be fixed in the next release.

For some reason your Steam configuration files are corrupted, which causes ProtonUp-Qt to crash. You can fix that for now by deleting certain files in the Steam config folder, see the linked issue for more information. Be aware that doing that may break something.

**Closed by DavidoTek** 2023-05-22 21:51 UTC
Labels: bug
