### ISSUE TITLE
ProtonUp-Qt 2.8.0 AppImage failes to work on Kubuntu 22.10

### ISSUE THREAD

**Issue by SegaGameBoyStation** [DavidoTek/ProtonUp-Qt#228] opened 2023-04-11 08:51 UTC
Please fill out following when reporting a new bug:

**Describe the bug**  
AppImmage version 2.8.0 fails to run on Kubuntu  22.10.
Dolphin reports that it doesn't exist. Running in konsole gives errors.
Permissions are set correctly.

**To Reproduce**  
1. Download latest app immage on Kubuntu.
2. try to run with permissions set.
3. Error

**Expected behavior**  
Application runs and shows window.

**Desktop (please complete the following information):**  
 - **Platform**: PC
 - **System**: Kubuntu 22.10
 - **Version**: ProtonUp-Qt 2.8.0
 - **How did you install ProtonUp-Qt?**:AppImage

**Additional context**  
I managed to run it once but unexpected behaviour such as the list of installed runtimes was blank while number showed howmany were installed. I couldn't down load any more. Closing and restarting makes it not run even after redownloading appimmage.

AppImage Launcher is on my system. Maybe related?

**Terminal output**  
`./ProtonUp-Qt-2.8.0_c0ea7a0613018528e0785140b81c69a9.AppImage     
ProtonUp-Qt 2.8.0 by DavidoTek. Build Info: Official AppImage by DavidoTek.
Python 3.8.2 (default, Mar 13 2020, 10:14:16) [GCC 9.3.0], PySide 6.2.4
Platform: Ubuntu 22.10 Linux-6.2.10-1-liquorix-amd64-x86_64-with-glibc2.29
Loading locale en / en_GB
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod D8VK (nightly)
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod NorthStar Proton (TitanFall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine)
Loaded ctmod Wine Tkg (Vanilla Wine)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Error: Could not get a list of all Steam apps: [Errno 2] No such file or directory: '/home/nightfiend6/.local/share/Steam/config/libraryfolders.vdf'
Traceback (most recent call last):
  File "/tmp/.mount_ProtonDFQ72q/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_ProtonDFQ72q/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_ProtonDFQ72q/usr/lib/python3.8/site-packages/pupgui2/__main__.py", line 2, in <module>
    main()
  File "/tmp/.mount_ProtonDFQ72q/usr/lib/python3.8/site-packages/pupgui2/pupgui2.py", line 549, in main
    MainWindow()
  File "/tmp/.mount_ProtonDFQ72q/usr/lib/python3.8/site-packages/pupgui2/pupgui2.py", line 108, in __init__
    self.update_ui()
  File "/tmp/.mount_ProtonDFQ72q/usr/lib/python3.8/site-packages/pupgui2/pupgui2.py", line 223, in update_ui
    get_steam_app_list(install_loc.get('vdf_dir'), cached=False)  # update app list cache
  File "/tmp/.mount_ProtonDFQ72q/usr/lib/python3.8/site-packages/pupgui2/steamutil.py", line 74, in get_steam_app_list
    apps.extend(get_steam_shortcuts_list(steam_config_folder, c))
UnboundLocalError: local variable 'c' referenced before assignment
Gamepad error: No gamepad found.
QThread: Destroyed while thread is still running
[appimagelauncher-binfmt-bypass/lib] ERROR: child exited with code 6
`

**Comment by DavidoTek** [comment] 2023-04-11 22:05
Close as duplicate of #226.

**Closed by DavidoTek** 2023-04-11 22:05 UTC
Labels: bug

**Comment by sonic2kk** [comment] 2023-04-12 14:39
Sorry to bump a closed issue, but is it definitely a duplicate? See this section of the Terminal output:

> `Error: Could not get a list of all Steam apps: [Errno 2] No such file or directory: '/home/nightfiend6/.local/share/Steam/config/libraryfolders.vdf'`

This is likely a problem with Steam rather than ProtonUp-Qt as Steam should generate these files. The rest of the issue appears to be the same as #226 though.

**Comment by SegaGameBoyStation** [comment] 2023-04-14 12:05
It could be a steam problem, however the older versions of ProtonUp-Qt worked fine. I did try the new version on both another distro (Garuda Linux) and a new user under Ubuntu and the latest version worked fine.
I am guessing that as my home partition has been copied over from one drive to another with each PC that I had for well over 15 years and across  various distros, that something changed in how steam is configured on Linux finally caught up with me.
I have noticed that steam default library path has changed to `~/.steam/debian-installation/steamapps/`

I did check and in new installs that directory path and file are not generated. I experimented for a bit and figured out that renaming the current .steam directory, completely removing steam in Synaptic and deleting both steam config folders, followed by reinstalling steam got the current version of ProtonUp-Qt to work as expected.

**Comment by sonic2kk** [comment] 2023-04-14 14:41
> I have noticed that steam default library path has changed to `~/.steam/debian-installation/steamapps/`

That shouldn't be the path to Steam, the path should be `~/.local/share/Steam/steamapps`. It sounds like something got messed up with your Steam installation.

**Comment by SegaGameBoyStation** [comment] 2023-04-18 02:42
> > I have noticed that steam default library path has changed to `~/.steam/debian-installation/steamapps/`
> 
> That shouldn't be the path to Steam, the path should be `~/.local/share/Steam/steamapps`. It sounds like something got messed up with your Steam installation.

I did some further testing with a new desktop user account on my PC and unistalling steam.
The path that I gave is how Steam from the Ubuntu repo is set up.  The path that you gave is how the Steam.deb downloaded from Steam's website is set up.

**Comment by sonic2kk** [comment] 2023-04-22 15:05
ProtonUp-Qt should still be checking `~/.steam/debian-installation`, but this does now seem to be the same as #226, which I guess boils down to library folders not being found.

#231 may fix the issue here since ProtonUp-Qt now checks for the given VDF files before it selects a Steam installation directory, but I'm not sure if it's working in the mentioned issue.

I'm not sure why Steam from the Ubuntu repo is different now.
