### ISSUE TITLE
[Crash] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 4608: invalid start byte

### ISSUE THREAD

**Issue by OldDragon88** [DavidoTek/ProtonUp-Qt#453] opened 2024-09-11 02:55 UTC
Please fill out following when reporting a new bug:

**Describe the bug**  
When I tried to launch ProtonUp-Qt it shows the following error and won't launch:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/lib/python3.11/site-packages/pupgui2/__main__.py", line 2, in <module>
    main()
  File "/app/lib/python3.11/site-packages/pupgui2/pupgui2.py", line 588, in main
    MainWindow()
  File "/app/lib/python3.11/site-packages/pupgui2/pupgui2.py", line 115, in __init__
    self.update_ui()
  File "/app/lib/python3.11/site-packages/pupgui2/pupgui2.py", line 249, in update_ui
    global_ctool_name: str = get_steam_global_ctool_name(install_loc.get('vdf_dir'))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/pupgui2/steamutil.py", line 221, in get_steam_global_ctool_name
    d = get_steam_vdf_compat_tool_mapping(vdf.load(open(config_vdf_file)))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/vdf/__init__.py", line 211, in load
    return parse(fp, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/vdf/__init__.py", line 97, in parse
    for lineno, line in enumerate(fp, 1):
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 4608: invalid start byte

``` 

**To Reproduce**  
1. flatpak run net.davidotek.pupgui2
2. Error as described

**Desktop (please complete the following information):**  
 - **Platform**: PC
 - **System**: Arch
 - **Version**: ProtonUp-Qt 2.10.0
 - **How did you install ProtonUp-Qt?**: Flatpak

**Comment by DavidoTek** [comment] 2024-09-11 08:25
It seems to be a duplicate of https://github.com/DavidoTek/ProtonUp-Qt/issues/424. I will reopen issue 424 to continue the discussion there as it appears to be still a problem.

Error in 424: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 2170: invalid start byte`
Your error: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 4608: invalid start byte`

**Closed by DavidoTek** 2024-09-11 08:25 UTC
Labels: bug
