### ISSUE TITLE
Luxtorpeda v59 installation stays eternally stuck on 99% (indicating "extracting")

### ISSUE THREAD

**Issue by heidiwenger** [DavidoTek/ProtonUp-Qt#120] opened 2022-08-31 21:48 UTC
ProtonUp-Qt 2.7.2 (flatpak). Restarting and attempting to reinstall does not help.
![Screenshot from 2022-09-01 00-47-54](https://user-images.githubusercontent.com/82445727/187791233-e5722313-c4d7-48f0-acd4-30941e4444b8.png)

**Comment by DavidoTek** [comment] 2022-08-31 21:54
Can you open a Terminal, run ProtonUp-Qt from there using `flatpak run net.davidotek.pupgui2` and post the output here?

**Comment by heidiwenger** [comment] 2022-08-31 21:56
> 

flatpak run net.davidotek.pupgui2
ProtonUp-Qt 2.7.2 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.9.9 (main, Nov 10 2011, 15:00:00) [GCC 11.3.0], PySide 6.3.1
Platform: Linux-5.15.61-217.current-x86_64-with-glibc2.33
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Proton Tkg
Loaded ctmod Roberta
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Gamepad error: No gamepad found.

**Comment by heidiwenger** [comment] 2022-08-31 22:05
Now when trying to install Luxtorpeda with that terminal open, there is added this after "No gamepad found":

[Errno 20] Not a directory: '/home/tux/.local/share/Steam/compatibilitytools.d/luxtorpeda'

**Comment by DavidoTek** [comment] 2022-09-01 17:26
Can you check if following folders exist and if one (or both) folders contain a `luxtorpeda` folder:
 - `/home/tux/.local/share/Steam/compatibilitytools.d`
 - `/home/tux/.steam/root/compatibilitytools.d`

**Comment by heidiwenger** [comment] 2022-09-03 16:55
> Can you check if following folders exist and if one (or both) folders contain a `luxtorpeda` folder:
> 
>     * `/home/tux/.local/share/Steam/compatibilitytools.d`
> 
>     * `/home/tux/.steam/root/compatibilitytools.d`

![lt2](https://user-images.githubusercontent.com/82445727/188280708-a8f377c3-3579-4870-93d9-8ff32566a3f6.png)
![lt1](https://user-images.githubusercontent.com/82445727/188280714-23a91c04-fd6b-4a4f-bc77-4a03b2f497df.png)

So, no, a folder "luxtorpeda" doesn't exist in either.

**Comment by DavidoTek** [comment] 2022-09-04 15:05
Looks like something went wrong there and the files weren't copied to a sub-directory. Did you install Luxtorpeda manually or using some other tool before using ProtonUp-Qt?

Can you delete all the files in the folder and try it again?

**Comment by heidiwenger** [comment] 2022-09-06 01:03
> 

No i didn't install Luxtorpeda manually before ProtonUp-Qt. 

But now, deleting all files on /home/tux/.local/share/Steam/compatibilitytools.d and launching ProtonUp, clicking to install Luxtorpeda, the installation finished! So 100%. Luxtorpeda now shows on the list. I wonder what should be done to prevent this bug from happening, then.

![Screenshot from 2022-09-06 04-02-23](https://user-images.githubusercontent.com/82445727/188525915-9d88df09-01fd-4cf6-ba55-5c7ba68050a8.png)

**Comment by DavidoTek** [comment] 2022-09-07 12:39
> I wonder what should be done to prevent this bug from happening, then.

Not sure what happened there, shouldn't be caused by the downloading mechanism of ProtonUp-Qt. It just extracts the archive contents, and all Luxtorpeda releases should contain a `luxtorpeda` folder.

I will close the issue for now, if it happens again we can reopen the issue.

**Closed by DavidoTek** 2022-09-07 12:39 UTC
Labels: bug
