### ISSUE TITLE
Very long start

### ISSUE THREAD

**Issue by VladimirMrzv** [DavidoTek/ProtonUp-Qt#60] opened 2022-04-25 14:55 UTC
Program start long time, this is reading folder proton from steam. If change to lutris or heroic than start faster. 
Version 2.5.0 and 2.6.0 start faster.

**Desktop (please complete the following information):**  
Ubuntu 22.04
ProtonUp-Qt 2.6.1 AppImage or Flatpak

Testing AppImage and flatpak versions. Old version only Appimage.

**Comment by DavidoTek** [comment] 2022-04-25 19:47
How many different Proton-GE versions do you have installed? A lot of them may increase the startup time.

Nevertheless, I will try to fix the issue in the next version of ProtonUp-Qt.

**Comment by VladimirMrzv** [comment] 2022-04-26 15:51
Thank you.
Wait for next release.

**Comment by VladimirMrzv** [comment] 2022-12-25 08:22
@DavidoTek 
Hope you see this comment.

In some last builds was broken "Show Game List" and at app begun run fast and operate in fast too. I think something wrong happened with read this list at startup.

**Comment by sonic2kk** [comment] 2023-01-09 20:50
I actually looked into this long start-up time a while ago just before the [`steam` dependency issue](https://github.com/DavidoTek/ProtonUp-Qt/pull/157). I believe the issue is related to the appinfo parser, I think there is some sort of bottleneck. This would also explain why Lutris is faster. Switching to Lutris, closing ProtonUp-Qt and then opening it again will save that Lutris was selected and so it will open faster. Switching to Steam freezes ProtonUp-Qt for around the same amount of time that it takes to open when Steam is selected, meaning it's fetching all of this data again most likely from the VDF file. 

Even on my Steam Deck it takes a long while for ProtonUp-Qt to open. In my case, the `appinfo.vdf` file is almost 25mb, so it's not hard to see why parsing this file could take time. I had a quick look in the file and it seems to have information about every game I own, as it has games I recently bought but that I never downloaded.

In the case of my Steam library, Steam says I have 1,514 games. There are probably a small handful of forgotten Steam shortcuts here but I would say that would only be 2 or 3. I got this figure by going to the library filters beside the search bar and for Steam Deck compatibility, I selected "All Games". This figure includes games that don't count towards the library count on your profile (games that the store lists as "Profile Features Limited"). 

If the `appinfo.vdf` contains information about 1,500+ games it would be no surprise why it takes so long for ProtonUp-Qt to open.

**Comment by DavidoTek** [comment] 2023-01-10 22:52
Okay, I took a look at the code.

The `appinfo.vdf` file gets parsed and it loops over all games in this file and gets a few values from the nested dict. This is done multiple times. It all happens in the `update_ui` function of the main window, this is why it could slow down the start.

If the problem should be caused by the appinfo file, we can cache the parsed app information and also maybe add an indicator that the file is loading.

> In the case of my Steam library, Steam says I have 1,514 games

I only have like 15 games on my machine.
Maybe, can you test the speed of the appinfo parser? Python code:

```python
from steam.utils.appcache import parse_appinfo
import time, os
file = os.path.expanduser('~/.steam/root/appcache/appinfo.vdf') # path to appinfo.vdf
t1 = time.time()
f =  open(file, 'rb')
header, apps = parse_appinfo(f)
t2 = time.time()
for steam_app in apps: # some code from steamutil.py
    try:
        name = steam_app.get('data').get('appinfo').get('common').get('name')
    except:
        pass
    try:
        dc = steam_app.get('data').get('appinfo').get('common').get('steam_deck_compatibility')
    except:
        pass

t3 = time.time()
print(f'parse_appinfo took {t2-t1} seconds, looping over all games took {t3-t2} seconds')
```

**Comment by sonic2kk** [comment] 2023-01-11 19:39
On my PC:

```python3
parse_appinfo took 1.4781951904296875e-05 seconds, looping over all games took 1.2314386367797852 seconds
```

It varied a tiny bit but it was always around 1.2-1.5s on my PC. I'm actually a bit surprised it was quite this fast so I checked to make sure it was definitely getting the game info and yeah, it seems to be working fine.

On my laptop, it was around 2.1s.

Maybe I was wrong and the VDF parser isn't the issue. Though waiting ~10 seconds isn't the worst thing in the world imo :-) I was fairly sure I narrowed it down before in the code to being this parser.

Though ProtonUp-Qt does still open instantly when Lutris is selected, I guess ProtonUp-Qt just does less checks when using Lutris. If I recall there's a good amount of stuff going on behind the scenes with the Steam game and tool checking, and less so for Lutris.

**Comment by DavidoTek** [comment] 2023-01-11 20:21
All right.

The actual parsing doesn't seem to be the problem, but rather the logic around it.

> If I recall there's a good amount of stuff going on behind the scenes with the Steam game and tool checking, and less so for Lutris.

It does [far more for Steam](https://github.com/DavidoTek/ProtonUp-Qt/blob/ef9ec0889a06363f12ae4e88e77cdc5ec8b2cf39/pupgui2/pupgui2.py#L198-L204) than for Lutris. It runs both `get_steam_game_list` and `get_steam_acruntime_list` once and then `get_steam_game_list` for each compatibility tool installed on every `update_ui` call. Both functions loop through all games multiple times (at least 3 times, more if you have more Steam library folders!).
If you consider that looping through all games once already took multiple seconds, that sums up to quite a lot, although the loops aren't similar complicated.

We need to see how we can improve this behavior.

Notes:
1. All three, `get_steam_game_list`, `get_steam_ctool_list` and `get_steam_acruntime_list` call `get_steam_app_list` once and then loop through all given apps to determine if the app is a game, a compatibility tool or a runtime.  
   We should avoid this and rather call `get_steam_app_list` with an argument that specifies whether we want a game, tool or runtime. This way we can already save one loop.
2. I don't think we can avoid the loop through all library folders, or looping through all games once to convert the `dict` to a `SteamApp`. Though we may be able to do this more efficient/in parallel if needed.
3. `update_steamapp_info` (called for each library folder by get_steam_app_list) loops thorugh all games to update information (game name, compatibility, type, etc.) about them. Part of this information is fetched using _get_steam_ctool_info which in turn also loops through all games once, although this infomation is cached in `_cached_steam_ctool_id_map` and only needs to be read once.
4. `update_steamapp_awacystatus` (called for each library folder by get_steam_app_list) opens the awacy json file and also loops through all games.

**Closed** 2023-01-19 13:42 UTC
Labels: bug

**Comment by nonetrix** [comment] 2026-01-06 22:54
I am still having long startup times, it's not the biggest issue but it shouldn't take longer than my web browser really

https://github.com/user-attachments/assets/76926115-bba8-428c-90ab-2fd223f5474c

A much more complex QT app like Prismlauncher is instant only starting in a few milliseconds
