### ISSUE TITLE
Installing proton-ge or northstar stuck at 99% "Errno 13"

### ISSUE THREAD

**Issue by roof98** [DavidoTek/ProtonUp-Qt#261] opened 2023-07-03 02:27 UTC
Please fill out following when reporting a new bug:

**Describe the bug**  
Attempting to install proton or northstar silence fails and hangs at 99%, console gives error 13
Attempting to run ProtonUP as sudo none of the dropdowns work. 

 - **Platform**: PC
EndevourOS
ProtonUp-Qt 2.8.0 via AUR

**Terminal output**  
[Errno 13] Permission denied: '/home/NAME/.local/share/Steam/compatibilitytools.d/GE-Proton8-6'

**Comment by sonic2kk** [comment] 2023-07-03 16:27
I just tested v2.8.0 from Flatpak and running from source with 65337e4a1f2ebcddef2f2a0c5626c5a7648ba326, and GE-Proton, Proton-tkg and NorthStar Proton installed fine for me on vanilla Arch Linux. I didn't try the unofficial AUR package.

This sounds more like a permissions issue based on the terminal output. Errno 13 does come from Python if I recall correctly when trying to perform file operations when there is insufficient permissions.

I would suggest checking the permissions on `~/.local/share/Steam/compatibilitytools.d`.

**Comment by Co3co** [comment] 2023-07-31 02:41
This is happening to me as well with Proton-TKG.

**Comment by sonic2kk** [comment] 2023-07-31 09:02
- What are the permissions on the folder you're trying to install the compatibility tool to?
- Can you recreate the issue with other compatibility tools being installed to the same folder (i.e. a GE Proton/Wine build)
- Are you also using a package from the AUR?
- What version of ProtonUp-Qt? 
- Can you reproduce the issue with the ProtonUp-Qt AppImage/Flatpak (in other words is this isolated to a specific build type)?
- Are you also trying to install Proton-tkg for Steam? Does it work with other launchers (i.e. Heroic)?

**Comment by 8836290** [comment] 2023-08-03 06:00
Using the .appimage version of ProtonUp-Qt and today I encountered the same issue while trying to download GE-Proton8-10

**Comment by sonic2kk** [comment] 2023-08-03 11:07
It would be helpful to post the exact error message (in case there are any subtle differences) and provide more information about the problem to help troubleshoot. Namely:
- Does the path in the error message exist (e.g. `'/home/NAME/.local/share/Steam/compatibilitytools.d`)
- If so, do the permissions on this folder look sane?
- Can you manually extract any archives to this folder?
- Does this happen with other versions of the same compatibility tool (e.g. GE-Proton8-9)
- Does this happen with other compatibility tools?
- if possible, can you test with other launchers (e.g. Lutris etc)?

I have not tried GE-Proton8-10 or the AppImage, but GE-Proton8-9 works for me with the Flatpak and from source.

**Comment by sonic2kk** [comment] 2023-08-03 16:22
> There is no error message. The download progress sticks to 99% indefinitely unless I close ProtonUp-Qt

Perhaps a silly question but you were definitely running from Terminal in this test, to verify there was no error output? If so, then this is probably a separate issue altogether. There would not be a visual pop-up for an error like this, and OP's comment listed the error under command line output, perhaps obvious but I am only calling it out _just_ in case you were running the AppImage from an application launcher and not with `./ProtonUp-Qt-...AppImage`.

>  Permissions on folder is not an issue
>
> The compatibilitytools.d folder already exists, I have older versions of GE-Proton already in there
>
> Yes manually extraction of GE-Proton from the archive was my "workaround"

Thanks for checking!

> I had no issue with older versions of GE-Proton

So you can still download GE-Proton8-9 etc, but when trying to download GE-Proton8-10, it fails. I just checked with the AppImage, Flatpak, and running from source, and I didn't have any problems with GE-Proton8-9 or GE-Proton8-10.

It is incredibly strange to me that only this one build for Steam fails.

<hr>

As for the other issues, thanks for checking. So this is specific to GE-Proton8-10 only, on Steam, with ProtonUp-Qt. Very odd, perhaps it's some kind of temporary issue with connecting to GitHub to fetch this specific build?

Nothing has changed on the GitHub side that would require a change, they are still packaged the same way, so we shouldn't need a code change to that end.

I tested with the v2.8.1 Flatpak and AppImage, downloading a couple different GE-Proton versions for each to Steam, and couldn't re-create the problem. Running from source @ a52cbc0c4036834572a6347969d67fae7c42c4b9 also worked. I tried renaming the `compatibilitytools.d` folder so ProtonUp-Qt would create it, and checked to ensure the permissions were correct on it and that ProtonUp-Qt could still download GE-Proton8-9 and GE-Prootn8-10 to it.

If there is no error output then I am not sure why it's failing. It could be some kind of network issue with GitHub.

<hr>

As an interesting separate note, I changed the permissions on the folder manually to read-only and got the same error that OP described.

**Comment by 8836290** [comment] 2023-08-04 14:22
Today a new version of GE-Proton 8-11 was published, so I opened ProtonUp-Qt and just deleted the old versions and installed the latest one. I run ProtonUp-Qt either by a simple folder I have downloaded the .appimage or the applications of Ubuntu, to which I have already integrated it since it make no since for me to run an .appimage through terminal. It will not run whatsoever on my system anyway. 

So  GE-Proton 8-11 was downloaded as expected. For test's shake I re-downloaded 8-10, after closing and rerunning ProtonUp-Qt and this time it was downloaded without issue!

**Comment by sonic2kk** [comment] 2023-08-04 16:17
It sounds like, in this instance, it was a network issue. It can happen sometimes. Glad it's working now though!

**Comment by 8836290** [comment] 2023-08-04 16:58
> It sounds like, in this instance, it was a network issue. It can happen sometimes. Glad it's working now though!

Is that so? I could not download it with ProtonUp-Qt  no matter how may times I tried, which was more than one, and I managed to download the file manually with one attempt.

**Comment by sonic2kk** [comment] 2023-08-04 19:41
If it didn't work before, but works now, I am not sure what else it could be to be honest. There hasn't been an update to ProtonUp-Qt anywhere either, at least as far as I can tell.

Connecting to GitHub via ProtonUp-Qt and via a browser are also different processes. It's possible something may have temporarily gone wrong with the GitHub API.

**Comment by Co3co** [comment] 2023-08-05 04:37
>     * Can you recreate the issue with other compatibility tools being installed to the same folder (i.e. a GE Proton/Wine build)

I am able to install GE Protons, but I have not tested any other ones.

>     * Are you also using a package from the AUR?

I am using protonup-qt 2.8.1 from Arch's repos (installed with pacman).

**Comment by 8836290** [comment] 2023-08-05 08:33
> If it didn't work before, but works now, I am not sure what else it could be to be honest. There hasn't been an update to ProtonUp-Qt anywhere either, at least as far as I can tell.
> 
> Connecting to GitHub via ProtonUp-Qt and via a browser are also different processes. It's possible something may have temporarily gone wrong with the GitHub API.

I have never encountered any issue at all while using older versions of ProtonUp-Qt. Nevertheless I will see in the future if the issue happens again and of course report here. If nothing significant and relevant to the, as stated on the release notes, " Overhaul of the UI and internal functions" then all is fine.

**Comment by sonic2kk** [comment] 2023-08-05 13:20
@8836290 I don't think overhauling the "internal functions" is really referring to anything relating to download-related code, certainly not for GE-Proton. You can see a full list of commits between [v2.8.0 and v2.8.1](https://github.com/DavidoTek/ProtonUp-Qt/compare/v2.8.0...v2.8.1), if you'd like to see in more detail what the changelog notes are referring to (). And since a version change did not resolve the issue, but rather a retry of the download after a while, I think this was some kind of temporary network issue. I hope that makes sense :-)

<hr>

@Co3co So it is only Proton-tkg failing to download for you with ProtonUp-Qt, giving the same "Permission denied" error? If so, can you test some of the other things I mentioned (checking directory permissions, trying Flatpak/AppImage, etc)?

Also, could you clarify which AUR package you are using, as there are two ([protonup-qt](https://aur.archlinux.org/packages/protonup-qt) and [protonup-qt-bin](https://aur.archlinux.org/packages/protonup-qt-bin)).

I'm also using Arch, so I can try out the AUR package if needs be to see if I can recreate the problem, as I cannot with ProtonUp-Qt from Flatpak or from source @ a52cbc0c4036834572a6347969d67fae7c42c4b9.

**Comment by Zepmann** [comment] 2023-08-05 15:47
Tested Arch AUR package protonup-qt-bin. Tried to install Proton Tkg 5769784208. Stops at 99%. Error:

```
Failed to extract tar file '/tmp/pupgui2.a70200/tkg_extract_tmp/proton_tkg_experimental.bleeding.edge.8.0.51656.20230804.tar': unknown compression type 'r'
```

The downloaded package extracts successfully manually using `tar xf tkg_extract_tmp/proton_tkg_experimental.bleeding.edge.8.0.51656.20230804.tar` .

**Comment by sonic2kk** [comment] 2023-08-05 15:48
Looks like it needs an update following #267.

**Comment by Zepmann** [comment] 2023-08-05 15:55
Looks like the patch needs to be included in a new version, so that protonup-qt-bin can rip the binaries from the AppImage release.

**Comment by Zepmann** [comment] 2023-08-05 16:07
Tested patch #267 by modifying AUR package protonup-qt and including it. The patch works for that as well.

**Comment by sonic2kk** [comment] 2023-11-06 20:29
Is this still an issue? I just tested and GE-Proton8-6 (the version from this issue), GE-Proton8-22 (the latest at time of writing), and NorthStar Proton (v8-20, not sure which version(s) had been tested with this issue) all installed successfully. I tested with ProtonUp-Qt v2.8.2 Flatpak, ProtonUp-Qt from source (`git clone https://github.com/DavidoTek/ProtonUp-Qt/ && cd ProtonUp-Qt && python3 -m pupgui2`), and the `protonup-qt` AUR package (`yay -S protonup-qt && protonup-qt`) -- I didn't test `protonup-qt-bin` but I imagine it works the same.

If anyone can still reproduce this behaviour, please comment :-)

**Closed** 2023-11-13 17:57 UTC
Labels: bug
