### ISSUE TITLE
ProtonUp-Qt-2.9.2-x86_64.AppImage doesn't start on Ubuntu 22.04-LTS

### ISSUE THREAD

**Issue by andyrozman** [DavidoTek/ProtonUp-Qt#399] opened 2024-05-16 21:52 UTC
Please fill out following when reporting a new bug:

**Describe the bug**  
When I try to start ProtonUp-Qt-2.9.2-x86_64.AppImage , I get exception.

**To Reproduce**  
1. Download: ./ProtonUp-Qt-2.9.2-x86_64.AppImage
2. Set permissions 
3. In Console run "./ProtonUp-Qt-2.9.2-x86_64.AppImage"

**Expected behavior**  
Application starts.

**Desktop (please complete the following information):**  
 - **Platform**: PC/Laptop
 - **System**: Ubuntu 22.04-LTS
 - **Version**: ProtonUp-Qt-2.9.2-x86_64
 - **How did you install ProtonUp-Qt?**: AppImage

**Additional context**  

**Terminal output**  
```
./ProtonUp-Qt-2.9.2-x86_64.AppImage
Traceback (most recent call last):
  File "/tmp/.mount_ProtonC5XfrF/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_ProtonC5XfrF/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_ProtonC5XfrF/usr/lib/python3.10/site-packages/pupgui2/__main__.py", line 1, in <module>
    from pupgui2.pupgui2 import main
  File "/tmp/.mount_ProtonC5XfrF/usr/lib/python3.10/site-packages/pupgui2/pupgui2.py", line 10, in <module>
    from PySide6.QtGui import QIcon, QKeyEvent, QKeySequence, QShortcut
ImportError: /home/andy/.local/lib/python3.10/site-packages/PySide6/Qt/lib/libQt6Core.so.6: version `Qt_6.7' not found (required by /tmp/.mount_ProtonC5XfrF/usr/local/lib/python3.10/dist-packages/PySide6/Qt/lib/libQt6DBus.so.6)```

**Comment by DavidoTek** [comment] 2024-05-16 21:54
Thanks for reporting.

That is probably a duplicate of https://github.com/DavidoTek/ProtonUp-Qt/issues/390 . The issue will be fixed with the next release version of ProtonUp-Qt.

Please use [v2.9.1](https://github.com/DavidoTek/ProtonUp-Qt/releases/tag/v2.9.1) or the Flatpak version until a newer version with the fix has been released.

**Closed by DavidoTek** 2024-05-16 21:54 UTC
Labels: bug

**Comment by andyrozman** [comment] 2024-05-17 07:45
After I posted ticket, I tried 2.9.1 App Image and that one worked for me.
