### ISSUE TITLE
does not run 

### ISSUE THREAD

**Issue by ghackt** [DavidoTek/ProtonUp-Qt#114] opened 2022-08-24 00:06 UTC
running latest 2.7 app opens then closes does not run

**Comment by DavidoTek** [comment] 2022-08-24 12:32
Are you using the AppImage version downloaded from GitHub or the one from your App Store (Flatpak)?

Probably duplicate of https://github.com/DavidoTek/ProtonUp-Qt/issues/112. Will be resolved in the next version.

**Comment by ghackt** [comment] 2022-08-24 17:13
> You can check if the following folder exists and delete it using the file manager/Dolphin.
> 
> `~/.var/app/net.davidotek.pupgui2/cache/tmp/pupgui2.a70200`

I will check this and reply back. Not sure what happened. I think it broke after a steam update. Also 3.4 is coming so may try to prepare for a preview edition update. Good software you have. I noticed it crashed when I tried to update the new 30 version from 29.

**Comment by ghackt** [comment] 2022-08-24 23:12
That worked interesting will there be a auto temp delete of folder during update installs in the future to eliminate this?

**Comment by DavidoTek** [comment] 2022-08-24 23:28
> will there be a auto temp delete of folder during update installs in the future to eliminate this?

Actually there is, but ProtonUp-Qt probably crashed at some point (maybe the Steam Deck went to sleep etc.) and it falsely thinks a second instance of the app is running.
The new version will detect this and ignore it.

**Closed** 2022-08-24 23:30 UTC
Labels: bug
